# These need to be in a certain order

include $(CWD)gmsl/gmsl
include $(CWD)config.mk
include $(CWD)utils.mk

include $(CWD)printing.mk
include $(CWD)error.mk

include $(CWD)dependencies.mk

include $(CWD)reloc.mk

include $(CWD)rules.mk
